# Generated by Django 5.1.4 on 2026-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, help_text='ID пользователя в Apple (sub-токен из Apple Sign In)', max_length=255, null=True, unique=True, verbose_name='Apple ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Подтверждён ли телефон через flash call или SMS', verbose_name='Телефон подтверждён'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_avatar_url',
            field=models.URLField(blank=True, help_text='URL аватара пользователя из соцсети (заполняется при первом входе)', max_length=500, verbose_name='Аватар из соцсети'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.CharField(blank=True, help_text='ID пользователя в VK (для входа через VK ID)', max_length=50, null=True, unique=True, verbose_name='VK ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='В международном формате, например: +79991234567', max_length=20, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
