# Generated by Django 5.1.4 on 2026-06-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_apple_id_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_avatar_url',
        ),
    ]
