# Generated by Django 6.0.6 on 2026-07-02 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_productstock'),
        ('sellers', '0002_sellerstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('pending_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('in_production', 'В производстве'), ('produced', 'Изготовлен'), ('assembling', 'Собирается'), ('shipped', 'Отгружен'), ('in_delivery', 'В доставке'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='pending_payment', max_length=30, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('refunded', 'Возвращён')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('delivery_method', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз')], max_length=20, verbose_name='Способ доставки')),
                ('delivery_address', models.CharField(blank=True, max_length=500, verbose_name='Адрес доставки')),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта адреса')),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота адреса')),
                ('delivery_comment', models.TextField(blank=True, verbose_name='Комментарий курьеру')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='ФИО получателя')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Телефон получателя')),
                ('payment_method', models.CharField(choices=[('card_online', 'Картой онлайн'), ('cash_on_delivery', 'Наличными при получении')], max_length=20, verbose_name='Способ оплаты')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма товаров')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость доставки')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итого')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('docnum_1c', models.IntegerField(blank=True, null=True, verbose_name='Номер документа в 1С')),
                ('synced_at_1c', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизировано с 1С')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Отгружен')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлен')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sellers.seller', verbose_name='Продавец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.warehouse', verbose_name='Склад отгрузки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=500, verbose_name='Название товара (snapshot)')),
                ('product_uuid_1c', models.UUIDField(verbose_name='UUID товара в 1С')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма позиции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, max_length=30, verbose_name='Предыдущий статус')),
                ('status_to', models.CharField(max_length=30, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда изменён')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='Изменён автоматически')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
