# Generated by Django 6.0.6 on 2026-07-06 06:39
from typing import ClassVar

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.operations.base import Operation
from django.db.migrations.state import StateApps


def migrate_old_statuses_forward(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Перевести старые статусы на новую архитектуру двух осей.

    Раньше status содержал оплату (pending_payment, paid).
    Теперь оплата — отдельная ось payment_status.

    pending_payment → created
    paid            → created + payment_status=paid
    """
    Order = apps.get_model("orders", "Order")

    Order.objects.filter(status="pending_payment").update(status="created")
    Order.objects.filter(status="paid").update(status="created", payment_status="paid")


def migrate_old_statuses_backward(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Обратный перевод для отката миграции.

    created → pending_payment (различие created/paid восстанавливается
    по payment_status).
    """
    Order = apps.get_model("orders", "Order")

    Order.objects.filter(status="created", payment_status="paid").update(status="paid")
    Order.objects.filter(status="created").update(status="pending_payment")


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("orders", "0002_order_cancelled_at"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("failed", "Не прошла"),
                    ("refunded", "Возвращён"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("in_production", "В производстве"),
                    ("produced", "Изготовлен"),
                    ("assembling", "Собирается"),
                    ("shipped", "Отгружен"),
                    ("in_delivery", "В доставке"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                ],
                default="created",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.RunPython(
            migrate_old_statuses_forward,
            migrate_old_statuses_backward,
        ),
    ]
