# Generated by Django 6.0.6 on 2026-07-06 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_status_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, max_length=20, verbose_name='Предыдущий статус оплаты')),
                ('status_to', models.CharField(max_length=20, verbose_name='Новый статус оплаты')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда изменён')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='Изменён автоматически')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История оплаты',
                'verbose_name_plural': 'История оплат',
                'ordering': ['-changed_at'],
            },
        ),
    ]
