# Generated by Django 6.0.6 on 2026-07-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymentstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_online', 'Картой онлайн'), ('sbp', 'СБП'), ('cash_on_delivery', 'Наличными при получении')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
