# Generated by Django 5.1.4 on 2026-06-02 21:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sellers', '0002_sellerstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_1c', models.UUIDField(blank=True, help_text='Идентификатор склада в системе 1С', null=True, unique=True, verbose_name='UUID в 1С')),
                ('name', models.CharField(help_text='Например: «Склад на Ленина, 5»', max_length=150, verbose_name='Название')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Точка на карте, где расположен склад', srid=4326, verbose_name='Координаты центра')),
                ('delivery_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Полигон территории, на которую этот склад доставляет курьером', null=True, srid=4326, verbose_name='Зона доставки')),
                ('pickup_available', models.BooleanField(default=True, help_text='Может ли покупатель забрать заказ с этого склада', verbose_name='Доступен самовывоз')),
                ('working_hours', models.JSONField(blank=True, help_text='Часы работы по дням недели в формате JSON', null=True, verbose_name='Часы работы')),
                ('contact_phone', models.CharField(blank=True, help_text='Телефон склада для покупателей при самовывозе', max_length=20, verbose_name='Контактный телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='sellers.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['seller__name', 'name'],
            },
        ),
    ]
