# Generated by Django 5.1.4 on 2026-06-03 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_warehouse'),
        ('sellers', '0002_sellerstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_1c', models.UUIDField(blank=True, help_text='Идентификатор товара в системе 1С (заполняется автоматически)', null=True, unique=True, verbose_name='UUID в 1С')),
                ('name_short', models.CharField(help_text='Для списков, каталога', max_length=255, verbose_name='Название краткое')),
                ('name_full', models.CharField(blank=True, help_text='Для карточки товара', max_length=500, verbose_name='Название полное')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('product_type', models.CharField(choices=[('stock', 'Со склада'), ('made_to_order', 'Под заказ (3D-печать)')], default='stock', max_length=20, verbose_name='Тип товара')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Цена из 1С (рубли)', max_digits=12, verbose_name='Базовая цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Если задана — используется вместо базовой цены', max_digits=12, null=True, verbose_name='Скидочная цена')),
                ('is_available_for_sale', models.BooleanField(default=True, help_text='Управляется из 1С: глобальный флаг доступности товара', verbose_name='Доступен к продаже (1С)')),
                ('is_active', models.BooleanField(default=True, help_text='Управляется в админке: можно скрыть товар, не меняя данные в 1С', verbose_name='Активен в системе')),
                ('production_time_days', models.IntegerField(blank=True, help_text='Только для товаров под заказ', null=True, verbose_name='Время изготовления (дней)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация с 1С')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sellers.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'is_active'], name='catalog_pro_seller__d5351a_idx'), models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'), models.Index(fields=['is_available_for_sale', 'is_active'], name='catalog_pro_is_avai_02d1af_idx')],
            },
        ),
    ]
