# Generated by Django 5.1.4 on 2026-06-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Остаток к продаже (за вычетом брака, приходит из 1С)', verbose_name='Количество')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Количество в активных заказах (ещё не отгружено)', verbose_name='В резервах')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складах',
                'ordering': ['product', 'warehouse'],
                'indexes': [models.Index(fields=['warehouse'], name='catalog_pro_warehou_63fd70_idx'), models.Index(fields=['product', 'warehouse'], name='catalog_pro_product_a8fc8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_product_warehouse_stock')],
            },
        ),
    ]
