# Generated by Django 6.0.6 on 2026-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productcharacteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Общее название витрины, например: Чехол iPhone 11 Pro Max', max_length=255, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Группа вариантов',
                'verbose_name_plural': 'Группы вариантов',
                'ordering': ['name'],
            },
        ),
    ]
