# Generated by Django 6.0.6 on 2026-07-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Объединяет варианты в одну карточку. Пусто — без вариантов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.productgroup', verbose_name='Группа вариантов'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_color',
            field=models.CharField(blank=True, help_text='Например: Жёлтый.', max_length=50, verbose_name='Цвет (вариант)'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_size',
            field=models.CharField(blank=True, help_text='Например: M.', max_length=50, verbose_name='Размер (вариант)'),
        ),
    ]
