# Generated by Django 6.0.6 on 2026-07-20 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_group_product_variant_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда искал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'История поиска',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='catalog_sea_user_id_492bd1_idx')],
            },
        ),
    ]
