# Generated by Django 5.1.4 on 2026-06-01 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_1c', models.UUIDField(blank=True, help_text='Уникальный идентификатор продавца в системе 1С', null=True, unique=True, verbose_name='UUID в 1С')),
                ('name', models.CharField(help_text='Например: ИП Иванов И.И.', max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, help_text='Для отображения покупателю, например: "Лавка Иванова"', max_length=100, verbose_name='Краткое название')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('ogrnip', models.CharField(max_length=15, unique=True, verbose_name='ОГРНИП')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено — товары продавца не отображаются в каталоге', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('admin_user', models.ForeignKey(blank=True, help_text='Пользователь, который управляет этим продавцом в админке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sellers', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['name'],
            },
        ),
    ]
