# Generated by Django 5.1.4 on 2026-06-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер заказов'), ('storekeeper', 'Кладовщик')], max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='sellers.seller', verbose_name='Продавец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник продавца',
                'verbose_name_plural': 'Сотрудники продавцов',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'seller'), name='unique_user_seller_role')],
            },
        ),
    ]
