# Generated by Django 6.0.6 on 2026-07-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellerstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='order_prefix',
            field=models.CharField(blank=True, help_text='Используется в номере заказа: BX-{префикс}-{год}-{номер}. Пример: "RYA"', max_length=8, verbose_name='Префикс заказов'),
        ),
    ]
