# Generated by Django 6.0.6 on 2026-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_populate_order_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='order_prefix',
            field=models.CharField(help_text='Используется в номере заказа: BX-{префикс}-{год}-{номер}. Пример: "RYA"', max_length=8, unique=True, verbose_name='Префикс заказов'),
        ),
    ]
