# Generated by Django 6.0.6 on 2026-07-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть отзыв от покупателей (модерация).', verbose_name='Опубликован'),
        ),
    ]
